#- name: Copy rpms files]
#  copy:
#    src: rpms/
#    dest: /home/centos/druid
#    owner: centos
#    group: centos
#    mode: 777

- name: clone rpms
  git:
    repo: 'https://github.com/galrabin/tddcom.git'
    dest: /home/centos/tddcom
    force: yes

- name: change rpms permissions
  file:
    path: /home/centos/tddcom
    owner: centos
    group: centos
    mode: '777'
    recurse: yes

- name: Download Epel repository
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /home/centos/tddcom/druid/ansible/roles/files/epel-release-latest-7.noarch.rpm
    mode: 777

- name: Install druid
  yum:
    name: "/home/centos/tddcom/druid/ansible/druid/roles/files/{{ item }}"
    with items:
    - epel-release-latest-7.noarch.rpm
    - libmicrohttpd-0.9.22-1.el7.centos.x86_64.rpm
    - curl-7.43.0-1.el7.x86_64.rpm
    - libcurl-7.43.0-1.el7.x86_64.rpm
    - sofia-sip-1.12.11-8.fc20.x86_64.rpm
    - raemis-default-4.2-1.CP11.x86_64.VIRTUAL.rpm

- name: hasp key for sending to druidd
  command: hasp_get_system_id
  register: key

- name: print key for druid liscence
  debug: msg="{{ key.stdout }}"